# Generated by Django 3.2.11 on 2022-01-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='input1',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='input2',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='oper',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterModelTable(
            name='calculation',
            table='Calculation',
        ),
    ]
