# Generated by Django 3.2.11 on 2022-01-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220117_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='status',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
