# Generated by Django 3.2.11 on 2022-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_calculation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='input1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='input2',
            field=models.IntegerField(),
        ),
    ]
